### ISSUE TITLE
Edit transforms image alpha channel

### ISSUE THREAD

**Issue by Gakk** [damienaicheh/azure-devops-launch-icon-badge#1]
Hi,

I tried your tool to add icon badge, and App Store Connect failed verifying the app:

`ERROR ITMS-90717: "Invalid App Store Icon. The App Store Icon in the asset catalog in 'MyApp.iOS.app' can't be transparent nor contain an alpha channel."`

Here are my before and after PNG-files:
- [before.png](https://user-images.githubusercontent.com/5013909/75773157-a0364e80-5d4d-11ea-8d02-ab73e6b2887f.png)
- [after.png](https://user-images.githubusercontent.com/5013909/75773155-9f052180-5d4d-11ea-97d9-92235036b783.png)

Using [ImageMagick](https://imagemagick.org/) i found out that my _before_ image actually contained an alpha channel of 1 bit, and App Store do accepted that as long as there are no transparent pixels. After running your tool the alpha channel had been transformed to 8 bit, and then App Store rejects it.

Excerpts from details running `magick identify -verbose *.png`:

**Image: before.png**
>  Colorspace: sRGB
>  Type: TrueColorAlpha
>  Depth: 8-bit
>  Channel depth:
>    Red: 8-bit
>    Green: 8-bit
>    Blue: 8-bit
>    _**Alpha: 1-bit**_

Complete details: [before.txt](https://github.com/damienaicheh/azure-devops-launch-icon-badge/files/4281090/before.txt)

**Image: after.png**
>  Colorspace: sRGB
>  Type: TrueColorAlpha
>  Depth: 8-bit
>  Channel depth:
>    Red: 8-bit
>    Green: 8-bit
>    Blue: 8-bit
>    _**Alpha: 8-bit**_

Complete details: [after.txt](https://github.com/damienaicheh/azure-devops-launch-icon-badge/files/4281089/after.txt)

Even when I removed the alpha channel before running it through your tool, an 8-bit alpha channel was added. For testing purpose I attach also image [magick.png](https://user-images.githubusercontent.com/5013909/75780144-2311d600-5d5b-11ea-9424-c9a8b18123f0.png) with removed alpha channel, and it's details:

**Image: magick.png**
>  Colorspace: sRGB
>  _**Type: TrueColor**_
>  Depth: 8-bit
>  Channel depth:
>    Red: 8-bit
>    Green: 8-bit
>    Blue: 8-bit

Complete details: [magick.txt](https://github.com/damienaicheh/azure-devops-launch-icon-badge/files/4281487/magick.txt)

Here are my build step:

```
steps:
- task: DamienAicheh.launch-icon-task.launch-icon-badge-task.LaunchIconBadge@1
  displayName: 'Launch Icon Badge'
  inputs:
    contents: 'App.iOS/Assets.xcassets/AppIcon.appiconset/*.png'
    bannerVersionNamePosition: topRight
    bannerVersionNameText: Beta
    bannerVersionNumberPosition: bottom
    bannerVersionNumberText: '$(Build.BuildNumber)'
    bannerVersionNumberColor: '#FFFFFF'
    bannerVersionNumberTextColor: '#919191'
```
