### ISSUE TITLE
bannerVersionNumberText is not displayed on Android

### ISSUE THREAD

**Issue by jamesjmtaylor** [damienaicheh/azure-devops-launch-icon-badge#6]
The task runs and updates the bannerVersionNameText, but not the bannerVersionNumberText.

This is the output from AzureDevOps:
```
Starting: Apply Launch Icon Version Badge
==============================================================================
Task         : Launch Icon Badge
Description  : Draw badge in your application launch icon.
Version      : 1.0.8
Author       : Damien Aicheh
Help         : 
==============================================================================
Edition succeeded for:/Users/runner/work/1/s/src/Sentinel.Droid/Resources/mipmap-hdpi/ic_launcher_foreground.png
Edition succeeded for:/Users/runner/work/1/s/src/Sentinel.Droid/Resources/mipmap-mdpi/ic_launcher_foreground.png
Edition succeeded for:/Users/runner/work/1/s/src/Sentinel.Droid/Resources/mipmap-xhdpi/ic_launcher_foreground.png
Edition succeeded for:/Users/runner/work/1/s/src/Sentinel.Droid/Resources/mipmap/ic_launcher_foreground.png
Edition succeeded for:/Users/runner/work/1/s/src/Sentinel.Droid/Resources/mipmap-xxxhdpi/ic_launcher_foreground.png
Edition succeeded for:/Users/runner/work/1/s/src/Sentinel.Droid/Resources/mipmap-xxhdpi/ic_launcher_foreground.png
Finishing: Apply Launch Icon Version Badge
```

Here are the Android round icons:
![droidRound](https://user-images.githubusercontent.com/17860994/140424130-9d16e7a6-c4de-428f-bca5-700d97c5be6f.png)

Here are the Android square icons:
![droidSquare](https://user-images.githubusercontent.com/17860994/140424195-ffd4a105-ec6c-4f23-b096-de673d9ea88e.jpeg)

Here is an example of iOS, which works:
![iOS](https://user-images.githubusercontent.com/17860994/140424224-31056f93-dd96-4e65-b6ef-fdf7db7df32b.jpeg)

I even tried hardcoding the bannerVersionNumberText, with the same result:
```
    - task: LaunchIconBadge@1
      displayName: 'Apply Launch Icon Version Badge'
      condition: |
        and(
          succeeded(),
          ne(variables['ENVIRONMENT_NAME'], 'PROD')
        )
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)/src/Sentinel.Droid/Resources/'
        contents: '**/ic_launcher_foreground.png'
        bannerVersionNameText: '$(ENVIRONMENT_NAME)'
        bannerVersionNameColor: '#ED4848'
        bannerVersionNameTextColor: '#FFFFFF'
        bannerVersionNumberPosition: 'top'
        bannerVersionNumberText: '13370'
        bannerVersionNumberColor: '#ED4848'
        bannerVersionNumberTextColor: '#FFFFFF'
```

**Comment by damienaicheh** [comment]
Did you try to publish the images from the Android app into Azure DevOps to see if something was drawn instead of looking at the icon in your Android device ?
I have two suppositions, the Android OS you use shrink your image so it's not visible or the number is two big and the result is two small because the algorithm behind try to center the text to see everything.

**Comment by jamesjmtaylor** [comment]
@damienaicheh I updated my pipeline to the following:

```
    - task: LaunchIconBadge@1
      displayName: 'Apply Launch Icon Version Badge'
      condition: |
        and(
          succeeded(),
          ne(variables['ENVIRONMENT_NAME'], 'PROD')
        )
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)/src/Sentinel.Droid/Resources/'
        contents: '**/ic_launcher_foreground.png'
        bannerVersionNameText: '$(ENVIRONMENT_NAME)'
        bannerVersionNameColor: '#ED4848'
        bannerVersionNameTextColor: '#FFFFFF'
        bannerVersionNumberPosition: 'top'
        bannerVersionNumberText: '1234'
        bannerVersionNumberColor: '#ED4848'
        bannerVersionNumberTextColor: '#FFFFFF'

    - task: Bash@3
      displayName: "Output android app icon to logs."
      inputs:
        targetType: "inline"
        script: |
          echo "##vso[task.uploadfile]/Users/runner/work/1/s/src/Sentinel.Droid/Resources/mipmap/ic_launcher_foreground.png"
```

The file that was output to the azure pipeline logs was:
![11_ic_launcher_foreground](https://user-images.githubusercontent.com/17860994/140547660-6142e2a8-c0f6-4ee1-8bcb-0d614729bc9c.png)

Looking at the icon on my Android device, it would appear that the number is cropped out. Do you know how I might remedy this?
